cutadapt:
  extra: ''

bwa:
  index: '/path/to/index'
  extra: ''
  sort_extra: ''
  threads: 5

picard_merge_bam:
  extra: ''

picard_mark_duplicates:
  extra: ''

freebayes:
  reference: '/path/to/genome.fasta'
  extra: ''

multiqc:
  extra: ''

fastqc:
  extra: ''
