input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: 'input'

  # Optional: configuration to use for remote (FTP) input files.
  # ftp:
  #   username: 'user'
  #   password: 'pass'


cutadapt:
  # Example trims Illumina Truseq PE adapters.
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    -q 20
    --minimum-length 60

bwa:
  index: '/path/to/index'
  # Note that MarkDuplicates requires the LB tag to be set.
  # Replace 'CENTRE' with the name of your company/institute.
  extra: "-r \"@RG\\tID:{sample}.{lane}\\tSM:{sample}\\tLB:{sample}\\t\
          PU:{sample}.{lane}\\tPL:ILLUMINA\\tCN:CENTRE\""
  sort_extra: ''
  threads: 5

picard_merge_bam:
  extra: '-XX:ParallelGCThreads=5'

picard_mark_duplicates:
  extra: >-
    -XX:ParallelGCThreads=5
    VALIDATION_STRINGENCY=LENIENT

freebayes:
  reference: '/path/to/genome.fasta'
  targets: '/path/to/capture.bed'
  extra: >-
    --min-alternate-fraction 0.1
    --min-alternate-count 3
    --min-coverage 10

fastqc:
  extra: ''

picard_collect_hs_metrics:
    reference: '/path/to/reference'
    bait_intervals: '/path/to/capture.intervals'
    target_intervals: '/path/to/capture.intervals'
    extra: '-Xmx4g'

multiqc:
  extra: ''
